#!/usr/bin/env fish

if [ "$argv[1]" = "zig" ]
    set container "devbox-zig"
else if [ "$argv[1]" = "julia" ]
    set container "devbox-julia"
else
    echo "Invalid argument."
    exit 1
end

set container_name "$container-"(basename (pwd))

if podman ps -a --format '{{.Names}}' | grep -q "^$container_name\$"
	if podman ps --format '{{.Names}}' | grep -q "^$container_name\$"
		echo "Container $container_name is already running."
		echo "Connect with `ssh guest@localhost -p 8000`"
		exit 0
	else
		echo "Container $container_name already exists. Starting it..."
		podman start $container_name
	end
else
    echo "Creating and starting a new container: $container_name"
    podman run -it -d -p 8000:22 -v $(pwd):/home/guest/$(basename $(pwd)):z --userns=keep-id --name $container_name $container
end

if podman ps --format '{{.Names}}' | grep -q "^$container_name\$"
	echo "Container $container_name is running."
	echo "Connect with `ssh guest@localhost -p 8000`"
end
