#!/usr/bin/env fish

if test -z "$argv[1]"
    echo "Usage: $0 <language>"
    exit 1
end

set image "devbox-"$argv[1]

if not podman image exists "$image"
    echo "Container image $image does not exist."
    exit 1
end

set container_name "$image-"(basename (pwd))

if podman ps -a --format '{{.Names}}' | grep -q "^$container_name\$"
	if podman ps --format '{{.Names}}' | grep -q "^$container_name\$"
		echo "Container $container_name is already running."
		echo "Connect with `ssh guest@localhost -p 8000`"
		exit 0
	else
		echo "Container $container_name already exists. Starting it..."
		podman start $container_name
	end
else
    echo "Creating and starting a new container: $container_name"
    podman run -it -d -p 8000:22 -v $(pwd):/home/guest/$(basename $(pwd)):z --userns=keep-id --name $container_name $image
end

if podman ps --format '{{.Names}}' | grep -q "^$container_name\$"
	echo "Container $container_name is running."
	echo "Connect with `ssh guest@localhost -p 8000`"
end
